<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname(dirname($vendorDir))));

return array(
    'Becopay\\PaymentGateway' => $vendorDir . '/becopay/invoice_sdk_php/src/PaymentGateway.php',
    'Becopay\\PaymentGatewayInterface' => $vendorDir . '/becopay/invoice_sdk_php/src/PaymentGatewayInterface.php',
);
