<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit165de0056ecaf387e690f5066f404323
{
    public static $prefixLengthsPsr4 = array (
        'b' => 
        array (
            'becopay\\gateway\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'becopay\\gateway\\' => 
        array (
            0 => __DIR__ . '/..' . '/becopay/invoice_sdk_php/src',
        ),
    );

    public static $classMap = array (
        'Becopay\\PaymentGateway' => __DIR__ . '/..' . '/becopay/invoice_sdk_php/src/PaymentGateway.php',
        'Becopay\\PaymentGatewayInterface' => __DIR__ . '/..' . '/becopay/invoice_sdk_php/src/PaymentGatewayInterface.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit165de0056ecaf387e690f5066f404323::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit165de0056ecaf387e690f5066f404323::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit165de0056ecaf387e690f5066f404323::$classMap;

        }, null, ClassLoader::class);
    }
}
